module.exports = {
    "gambler":{
        "ATTITUDE":0.7,
        "LIFESTYLE":1,
        "RELATIONSHIPS":0,
        "SECURITY":0,
        "SOCIALRESPONSIBILITY":0.1,
        "IDENTITY":0.1,
         "weight":2.5
    },
    "saver":{
        "ATTITUDE":0.2,
        "LIFESTYLE":0,
        "RELATIONSHIPS":0.1,       
        "SECURITY":1,
        "SOCIALRESPONSIBILITY":0.4,
        "IDENTITY":0,
        "weight":1.6
    },
    "manager":{
        "ATTITUDE":0.3,
        "LIFESTYLE":0.5,
        "RELATIONSHIPS":0.5,
        "SECURITY":0.6,
        "SOCIALRESPONSIBILITY":0,
        "IDENTITY":0.1,
        "weight":2.4
    },
    "influencer":{
        "ATTITUDE":0,
        "LIFESTYLE":0.1,
        "RELATIONSHIPS":1,
        "SECURITY":0.2,
        "SOCIALRESPONSIBILITY":0.8,
        "IDENTITY":0.1,
        "weight":2.2
    },
    "spender":{
        "ATTITUDE":0.8,
        "LIFESTYLE":1,
        "RELATIONSHIPS":0.1,
        "SECURITY":0,
        "SOCIALRESPONSIBILITY":0.2,
        "IDENTITY":0.8,
        "weight":2.9
    }
}